apiVersion: v1
kind: Service

metadata:
  name: dealmind-frontend
  namespace: dealmind

spec:
  selector:
    app: dealmind-frontend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP